version: "3.8"

services:
  dashboard:
    build: ./dashboard
    ports:
      - "8000:8000"
    env_file:
      - .env

  scheduler:
    build: ./scheduler
    env_file:
      - .env

  worker:
    build: ./worker
    env_file:
      - .env
